services:
  node:
    build:
      context: .
      target: base
      # args:
      #   - name=value
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/app
    command: ./init.sh
    init: true
    profiles:
      - lts
  node-19:
    build:
      context: .
      target: base
      # args:
      #   - name=value
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/app
    command: ./init.sh
    init: true
    profiles:
      - nextVersion
  node-live:
    build:
      context: .
      target: live
      # args:
      #   - name=value
    image: tanarurkerem/nest:latest
    profiles:
      - live
  node-test:
    build:
      context: .
      target: test
      # args:
      #   - name=value
    image: tanarurkerem/nest:test
    profiles:
      - test
