#https://github.com/tanarurkerem/docker-2023-06-06
services:
  adminer:
    image: adminer
    ports:
      - 127.0.0.1:8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  web:
    build: ./web
    environment:
      - NAME=Istvan
      - VIRTUAL_HOST=web.l.wdh.hu
  web2:
    build: ./web
    environment:
      - NAME=Lilla
      - VIRTUAL_HOST=web2.l.wdh.hu

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  data: