services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  admin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 127.0.0.1:80:80